export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_CHARACTER_PENDING = 'REQUEST_CHARACTER_PENDING';
export const REQUEST_CHARACTER_SUCCESS = 'REQUEST_CHARACTER_SUCCESS';
export const REQUEST_CHARACTER_FAILED = 'REQUEST_CHARACTER_FAILED';


